name: Python tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install coverage
      - name: Run tests with coverage
        run: |
          coverage run -m --branch unittest discover -s tests
          coverage report --fail-under=80
          coverage xml
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          flags: unittests # optional
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
